### PR TITLE
ModNewsAPI

### PR DESCRIPTION
**Pull request by aiteron**

### CODE REVIEW

**Comment by quarantin** [comment]
In translation files, sometime there's a comma at end of line, and sometimes not. Maybe both are OK I'm not sure, but I think it would be best to use either comma or not, but not having both mixed up. Your thoughts?

**Comment by Konijima** [comment]
> In translation files, sometime there's a comma at end of line, and sometimes not. Maybe both are OK I'm not sure, but I think it would be best to use either comma or not, but not having both mixed up. Your thoughts?

Can you specify a line of code that this apply to please?
Not sure to understand what you mean here.

**Comment by quarantin** [comment]
https://github.com/Konijima/PZ-Community-API/pull/54/files#diff-3207e9660ef72ab967c8df840fbe14e6cd14ea9f0d8c3a4194d016bbfd2a1b51R8

**Comment by quarantin** [comment]
Best would be to remove the commas IMHO, because they're not needed. It's not JSON.

**Comment by quarantin** [comment]
<pickyMode>And ModNewsButton.lua is missing a newline character at end of file.</pickyMode>

**Comment by quarantin** [comment]
Finally, and then I'll stop being picky (feel free to tell me if its bothering you), I would rebase the branch to squash commits that we don't need to see in changelog, like no need to have multiple commits to edit the README.md for instance, etc. Also no need to reference a fix for a bug that was introduced in the same pull request etc.

**Comment by quarantin** [comment]
Sorry one more, I can spot a few problems with indentation, for example these lines:
https://github.com/Konijima/PZ-Community-API/pull/54/files#diff-6ad848317ac690bd43febe87ea2fca02c9245baebcdf4dcca88d0705348c93a0R11
https://github.com/Konijima/PZ-Community-API/pull/54/files#diff-6ad848317ac690bd43febe87ea2fca02c9245baebcdf4dcca88d0705348c93a0R21
There's probably others.

**Review by Chuckleberry-Finn — APPROVED** [review]
Looks good.

**Pull request merged**
